### ISSUE TITLE
corpora_compare function - Issues and Comments

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/coRPysprofiling#21]

**Comment by eboylestanley** [comment]
Initial tests and code written #20

**Comment by eboylestanley** [comment]
@jkim222383 Do you have any thoughts/suggestions on using the SentenceTransformer embedding on longer sections of text (i.e. a paragraph or full paper).  After reviewing the documentation I am not sure it is appropriate to embed text longer than 1 sentence as a (1, 768) dimensional vector.  I could parse the longer text into individual sentences and embed each sentence. 
 But this will cause issues with the distance calculation if the input corpora don't have the same number of sentences.  `ValueError: shapes (3,768) and (1,768) not aligned: 768 (dim 1) != 1 (dim 0)`

**Comment by jkim222383** [comment]
> @jkim222383 Do you have any thoughts/suggestions on using the SentenceTransformer embedding on longer sections of text (i.e. a paragraph or full paper). After reviewing the documentation I am not sure it is appropriate to embed text longer than 1 sentence as a (1, 768) dimensional vector. I could parse the longer text into individual sentences and embed each sentence.
> But this will cause issues with the distance calculation if the input corpora don't have the same number of sentences. `ValueError: shapes (3,768) and (1,768) not aligned: 768 (dim 1) != 1 (dim 0)`

I thought about this a little and I think for our purpose, it'd okay to leave it as it is because of the dimension mismatch issue if the length of the corpora do not match. I tried a few cases with varying paragraph lengths and for our purpose, I believe the results given by treating each corpus as one whole sentence are consistent with the expected behaviour.
