### ISSUE TITLE
Initiate package review request

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/coRPysprofiling#49]

**Comment by ssyayayy** [comment]
Submitting Author: Ivy Zhang (@ssyayayy)
Other Authors: Anita Li (@AnitaLi-0371), Elanor Boyle-Stanley (@eboylestanley), Junghoo Kim (@jkim222383)
Package Name: coRPysprofiling
One-Line Description of Package: coRPysprofiling performs EDA and EDV on text
Repository Link:  https://github.com/UBC-MDS/coRPysprofiling/pulse
Version submitted:   
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

## Description

- coRPysprofiling is an open-source library designed to bring exploratory data analysis and visualization to the domain of natural language processing. Functions in the package will be used to provide some elementary statistics and visualizations for a single text corpus or provide functions to compare multiple corpora with each other.

## Scope 
- Please indicate which [category or categories][PackageCategories] this package falls under:
	- [X] Data retrieval
	- [ ] Data extraction
	- [ ] Data munging
	- [ ] Data deposition
	- [ ] Reproducibility
	- [ ] Geospatial
	- [ ] Education
	- [X] Data visualization*

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences):
> The core functionalities for coRPysprofiling are to provide elementary statistics and visualizations for a single text corpus, and to compare multiple corpora with each other. It can also download and load pretrained word2vector models from github repository.
-   Who is the target audience and what are scientific applications of this package?  
> The target audience can be talent acquisition specialists who want to quickly retrieve valuable information from resume texts or compare text from two resumes.
-   Are there other Python packages that accomplish the same thing? If so, how does yours differ?
> `Pandas-profiling` provides exploratory data analysis (EDA) such as basic statistics and visualizations to data frames. Ours tailors to provide EDA on text. 
-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or `@tag` the editor you contacted:

## Technical checks

For details about the pyOpenSci packaging requirements, see our [packaging guide][PackagingGuide]. Confirm each of the following by checking the box.  This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [X] has an [OSI approved license][OsiApprovedLicense].
- [X] contains a README with instructions for installing the development version. 
- [X] includes documentation with examples for all functions.
- [ ] contains a vignette with examples of its essential functions and uses.
- [X] has a test suite.
- [ ] has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.

## Publication options

- [ ] Do you wish to automatically submit to the [Journal of Open Source Software][JournalOfOpenSourceSoftware]? If so:

<details>
 <summary>JOSS Checks</summary>  

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements][JossSubmissionRequirements]. Be aware that completing the pyOpenSci review process **does not** guarantee acceptance to JOSS. Be sure to read their submission requirements (linked above) if you are interested in submitting to JOSS.
- [ ] The package is not a "minor utility" as defined by JOSS's [submission requirements][JossSubmissionRequirements]: "Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable." pyOpenSci welcomes these packages under "Data Retrieval", but JOSS has slightly different criteria.
- [ ] The package contains a `paper.md` matching [JOSS's requirements][JossPaperRequirements] with a high-level description in the package root or in `inst/`.
- [ ] The package is deposited in a long-term repository with the DOI: 

*Note: Do not submit your package separately to JOSS*
  
</details>

## Are you OK with Reviewers Submitting Issues and/or pull requests to your Repo Directly?
This option will allow reviewers to open smaller issues that can then be linked to PR's rather than submitting a more dense text based review. It will also allow you to demonstrate addressing the issue via PR links.

- [x] Yes I am OK with reviewers submitting requested changes as issues to my repo. Reviewers will then link to the issues in their submitted review.

## Code of conduct

- [X] I agree to abide by [pyOpenSci's Code of Conduct][PyOpenSciCodeOfConduct] during the review process and in maintaining my package should it be accepted.

**Comment by ssyayayy** [comment]
Opened the request to software-review-2021 repository: https://github.com/UBC-MDS/software-review-2021/issues/38
Will close this issue.

**Comment by ssyayayy** [comment]
Update release version to 0.1.6 in the package review request.
